[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
automod = "1.0"
itertools = "0.13.0"
regex = "1.11.1"
aoc_macros = { path = "./aoc_macros" }
glam = "0.29.2"
criterion = "0.5.1"
clap = { version = "4.5.23", features = ["derive"] }
rug = "1.26.1"
